services:
  growtogether-db:
    container_name: growtogether-db
    image: postgres:14.18
    restart: always
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=GrowToGether
    networks:
      - growtogether-network
    ports:
      - "5432:5432"  # ✅ เปิดให้ local backend connect ได้
    volumes:
      - growtogether:/var/lib/postgresql/data

volumes:
  growtogether:

networks:
  growtogether-network:
