services:
  growtogether_Backend:
    container_name: growtogether_backend
    image: growtogether-backend:latest
    networks:
     - growtogether-network
    ports:
      - "3000:3000"
    depends_on:
      - growtogether-db
    env_file:
      - .env.production


  growtogether_Fontend:
    container_name: growtogether_Fontend
    image: grow-app:latest
    networks:
     - growtogether-network
    ports:
      - "5173:5173"
    depends_on:
      - growtogether-db
    env_file:
      - .env.production


  growtogether-db:
    container_name: growtogether-db
    image: postgres:14.18
    environment:
      -  POSTGRES_PASSWORD=1234
      -  POSTGRES_USER=postgres
      -  POSTGRES_DB=GrowToGether
    networks:
     - growtogether-network
    volumes:
      - growtogether:/var/lib/postgresql/data

volumes: 
  growtogether:

networks:
  growtogether-network:
  